# Use only locally.

version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


volumes:
  db-data:
